version: 2
updates:
- package-ecosystem: npm
  directory: "/landing"
  schedule:
    interval: monthly
    time: "06:00"
  open-pull-requests-limit: 99
  reviewers:
  - rschlaefli
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/docs/website"
  schedule:
    interval: monthly
    time: "06:00"
  open-pull-requests-limit: 99
  reviewers:
  - rschlaefli
  versioning-strategy: increase
